### PR TITLE
Mesh grid

### PR DESCRIPTION
**Pull request by InsanityAutomation**
dgus code totally divorced and files reverted back to head, platformio and defines for has_dgus all resolved to only include whats needed
mesh grid screens added
means ubl support

### CODE REVIEW

**Comment by Sebazzz** [comment]
So this adds the mesh display instead of the visualisation while leveling, right?

**Comment by InsanityAutomation** [comment]
Thats correct, and goes with the screen files sent on discord

**Comment by Sebazzz** [comment]
We need to think about how this will affect the CR-6 MAX users @grobux - perhaps fall back to the graphical display for the CR-6 MAX users.

**Comment by BubuMVX** [comment]
Yes, I think we don't have enough space to write so much values without losing readability on the Max (smaller font = just a blob of pixels). Maybe we can only display the last measurement(s?), or only the center and the corners (the feature lose some interest that way...). I think about it.

**Comment by InsanityAutomation** [comment]
Ill have to look at the Max grid density, but what I did with the CR10-Max was 11x11 and showed only even indexes.

**Comment by Sebazzz** [comment]
Committed the relevant portion on a temporary feature branch in commit 7b1d5d0 pending work from @grobux so I can happily tweak away in extui without causing potential issues for myself. Feel free to branch from the feature branch in case you need to make additions.

**Comment by Sebazzz** [comment]
Thanks taken up further in #148 - indeed we need to depart from DGUS default

**Pull request closed without merging**
