### PR TITLE
Add support for Creality CR-200B

### PR DESCRIPTION
**Pull request by pienjo**
### Description

This PR adds support for the Creality CR-200B, which comes with the same DGUS screen as a CR6-SE, except that it is mounted in a horizontal configuration. 

This printer comes with a slightly different mainboard (Creality v. 4.2.5), which is *very* similar to a 4.2.10 board from a CR-30; The main difference is that the CS line for the SD card has moved to PC9.

This printer is also wired slightly differently:

- The Z-Min endstop is actually connected to the Z-Min header, not to the optical endstop header.
- There is an LED-strip connected to PC14
- There is a secondary enclosure fan, connected to PC0
- There is no probe. 

### Requirements

A Creality CR-200b printer, using the stock display and the stock mainboard. The display needs to be updated to the latest firmware from the CR6Community/CR-6-Touchscreen repository.

### Benefits

The DGUS code assumed that all printers have a probe - and the CR200B doesn't have one. The meat of this PR deals with disabling the probe-related code in case the configuration doesn't have a probe. When HAS_PROBE is not enabled, the live Z-offset adjustment is performed by babystepping instead. This is not ideal as this isn't stored in NVRAM. An alternative would be to use the workspace offsets from M206, but that was more invasive.

### Configurations

Configuration is stored in config/cr200b-v4.2.5-mb

### Related Issues

Note that there are a few remaining issues, but they are not really related to this specific printer or this repository:

- The screen is rotated 90 degrees - this will require a separate DWIN set for landscape displays. 
- The enclosure fan cannot be adjusted via the touchscreen.
- Even though the touchscreen menu suggests otherwise, all bed leveling is done by probing - which doesn't work on this printer, lacking a probe. On printers like this it would probably need a simple but separate bed levelling menu which offers shortcuts to move the nozzle to the 4 corners of the bed at Z=0, so the user can manually dial in the bed levelling screws. I didn't address this, as it would have required modifying the touchscreen firmware. 

That said: even with the limitations mentioned above, this is a *huge* step forward over the original fimware and touchscreen menu - you did an awesome job there.

### CODE REVIEW

**Comment by Sebazzz** [comment]
Awesome! Give me a moment to take a look at it.

**Comment by Sebazzz** [comment]
> The screen is rotated 90 degrees - this will require a separate DWIN set for landscape displays.

Yes, but that is unfortunately also a lot of work. One does not simply flick a switch - it would be a complete rebuild and redesign of the touch screen firmware.

**Comment by pienjo** [comment]
I know - I've been through it all; I have a landscape touchscreen firmware
ready to go

**Comment by piotrkpaul** [comment]
> I know - I've been through it all; I have a landscape touchscreen firmware ready to go

Is this landscape touchscreen firmware publicly available?

**Comment by Sebazzz** [comment]
@piotrkpaul Looks to be at: https://github.com/pienjo/CR-6-touchscreen

**Comment by piotrkpaul** [comment]
Thanks! I've build it from this branch but just after bootup, screen gets rotated. 
@pienjo do you have any solution for this? I'm running vanilla Marlin from your branch with stock CR-200B config
WhatsApp Image 2021-12-17 at 01 03 43
.

**Comment by Sebazzz** [comment]
Have you adjusted the screen orientation setting in Configuration.h?

Met vriendelijke groet,
Sebastiaan Dammann
________________________________
Van: Piotr Paul ***@***.***>
Verzonden: Friday, December 17, 2021 1:05:10 AM
Aan: CR6Community/Marlin ***@***.***>
CC: Sebastiaan Dammann ***@***.***>; State change ***@***.***>
Onderwerp: Re: [CR6Community/Marlin] Add support for Creality CR-200B (#277)


Thanks! I've build it from this branch but just after bootup, screen gets rotated.
@pienjo<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpienjo&data=04%7C01%7C%7C7e8ef7e54a174e3c9d8708d9c0f0e491%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637752963117191361%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Z4Y0pX6MhPX9AkUC%2B41FzN2Xc8xjd735UJpGYKCxQ6Q%3D&reserved=0> do you have any solution for this? I'm running vanilla Marlin from your branch with stock CR-200B config
[WhatsApp Image 2021-12-17 at 01 03 43]<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F865508%2F146466834-ea56ad9c-e291-4ac2-a67b-4ec8ef665f9c.jpeg&data=04%7C01%7C%7C7e8ef7e54a174e3c9d8708d9c0f0e491%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637752963117191361%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Wr0jl2axqNjRe6W2Q89y0ngxPWUZ14E7v%2F%2By%2BvZoA98%3D&reserved=0>
.

**Comment by piotrkpaul** [comment]
Yes - it is (`DGUS_LCD_UI_CREALITY_TOUCH_ORIENTATION`) by default set to 0. To be honest, Marlin loads fine, and after 2 second from startup screen gets rotated as on picture - like it was a glitch. When I'm clicking randomly on the left side of a screen (left upper part of user interface) it goes black, reboots and loads in proper orientation. 

It happens on every boot. Load sceen (with progress bar) is displayed in proper orientation.

edit:

Actually it's very similar to this bug - https://github.com/CR6Community/Marlin/issues/284 but screen gets flipped to different side.

Way less dramatic picture of this issue:


Bug reproduction video: https://www.youtube.com/watch?v=HXud05Ejutg

**Comment by pienjo** [comment]
Hi Piotr;

There's two possible reasons this could happen, judging by other people who had the same thing:

- Copying the contents of the DWIN_SET directory doesn't work, you'll have to use the Build.ps1 script
- The kernel of the touchscreen needs to be updated (this is probably what's causing this). The easiest way to obtain this file is by retrieving a release from the CR6 community firmware for the CR6-SE; it contains the kernel update in the distribution.

By the way: If you use the HEAD from my CR-6-touchscreen github, please be advised that it may not work correctly with this branch; it's supposed to work together with my fork of the CR-6 SE firmware which has diverged a bit.

**Comment by Sebazzz** [comment]
@piotrkpaul Please try to rebuild latest

**Comment by piotrkpaul** [comment]
> Hi Piotr;
> 
> There's two possible reasons this could happen, judging by other people who had the same thing:
> 
> * Copying the contents of the DWIN_SET directory doesn't work, you'll have to use the Build.ps1 script
> * The kernel of the touchscreen needs to be updated (this is probably what's causing this). The easiest way to obtain this file is by retrieving a release from the CR6 community firmware for the CR6-SE; it contains the kernel update in the distribution.
> 
> By the way: If you use the HEAD from my CR-6-touchscreen github, please be advised that it may not work correctly with this branch; it's supposed to work together with my fork of the CR-6 SE firmware which has diverged a bit.

I've already did both - updated kernel and flashed with package that came from build script.

> @piotrkpaul Please try to rebuild latest

I'll do and report back.

**Pull request merged**
