### PR TITLE
Cr 6 max

### PR DESCRIPTION
**Pull request by dabbodev**
### Requirements

* Filling out this template is required. Pull Requests without a clear description may be closed at the maintainers' discretion.

### Description

Reconfiguration for CR-6 MAX as well as fixed bed leveling and heating

### Benefits

It works

### Related Issues

This works with the new creality board 4.5.3

### CODE REVIEW

**Comment by Sebazzz** [comment]
Thanks for your PR - I got the Creality v4.5.3 bord working already using the official sources 🙂 Otherwise I think that changing the bed size should be sufficient, shouldn't it?

**Comment by dabbodev** [comment]
Could you try it with my leveling adjustments and see if you notice the
difference?

**Comment by Sebazzz** [comment]
What are the leveling adjustments? Is that `TOTAL_PROBING` set to 3?

**Comment by 64Spaces** [comment]
My CR-6 Max is still on the boat. Doesn’t it need a lot more Bed Leveling points, something like 36?

**Comment by Sebazzz** [comment]
> 
> 
> My CR-6 Max is still on the boat. Doesn’t it need a lot more Bed Leveling points, something like 36?

It does in this configuration, but the `TOTAL_PROBING` I'm referring to does 3 taps per point.

**Comment by dabbodev** [comment]
I had a few issues with FIX_MOUNTED_PROBE so I reworked it with
NOZZLE_AS_PROBE which required a couple other changes. The probing count
increase from 2 to 3 is just to get a more accurate average per point
instead of 1 fast 1 slow it does 1 fast and 2 slow and takes the average of
the 2 slow ones

**Comment by dabbodev** [comment]
My z offset on my printer is now -0.5 with the changes

**Comment by Sebazzz** [comment]
What do you think of the changes @InfinityAutomation, in light of your PR upstream?

**Comment by Sebazzz** [comment]
What do you think of the changes @InsanityAutomation, in light of your PR upstream?

**Comment by InsanityAutomation** [comment]
Seems to be mainly stuff already done, switching to nozzle as probe and the 453 pins, however those should be separate as already discussed. Otherwise, this should be a separate config file next to the CR6SE ones.

**Comment by InsanityAutomation** [comment]
Dug a bit more, G29 retry and recover is using default scripts. This machine doesnt have a wiper pad. If probing fails, a script could possibly go up and re-tare . Also, given the lack of display feedback in the process and potential danger with ramming the nozzle into the bed repeatedly with the strain gauge id consider this setup a poor candidate for that feature. A probe failure should be evaluated to avoid burning holes in the bed.

**Comment by dabbodev** [comment]
So should I remove the retry? I didn't know there was an issue with it. I
also don't have the printer heating up to level as it kept making the
strain gauge more inaccurate over time

**Comment by InsanityAutomation** [comment]
The retry would need some changes to line up with this hardware, and even then given the likely things to cause it to fail it would not likely be safe to retry.

The bed will move as it heats, and the nozzle will need to be hot enough for filament from the prior print to not contact before the known nozzle point. I dont see how heating can be avoided. We have played with heaters off while probing, which turns off heat while doing the downward move and recovers when going up and to the next point. It does ass significant amounts of time to the probe process, however if accuracy improvement shows its necessary the recommendation will be to work from a stored mesh and only repeat G29 in unusual circumstances, such as after a crash or nozzle change.

**Comment by dabbodev** [comment]
What i ended up doing with my printer is i basically made an anti-backlash
screw for the strain gauge. It seems to help a bit, but i also haven't
tried it with heating up before leveling I'll give that a shot as well.

**Comment by Sebazzz** [comment]
Sorry, it took me a while to get back at you because I was busy rebasing on top of upstream Marlin.

I've done that and pushed an empty branch [`extui-cr6-max`](https://github.com/CR6Community/Marlin/tree/extui-cr6-max) to the repository. Can you fork from that branch, do the changes necessary for the CR-6 Max (which at this point would probably be only be the correct motherboard, grid leveling size, and the bed size), and re-submit the pull request? 

Thanks and sorry for the inconvenience @dabbodev - but parallel to your PR some things got already merged to upstream Marlin so I had to take care of that! 😥

**Comment by dabbodev** [comment]
Sure one sec

**Pull request closed without merging**
