### PR TITLE
Implement FR - Issue#302

### PR DESCRIPTION
**Pull request by Thinkersbluff**
### Description

Increase the amount primed from 2mm to 15mm before drawing the Bed Mesh Validation pattern.
Add a prompt for the user to remind them to get their tweezers ready, to remove the drool and the primed amount, before the extruder begins drawing the pattern.

Implement this change as follows:

Modify line 72 of MeshValidationHandler.cpp to replace P2 with P15
Modify line 80 of MeshValidationHandler.cpp to add "Prepare tweezers" to the "Starting..." message.<!--

### Requirements

No special requirements.

### Benefits

See Issue #302.

### Configurations

Use the CF6.1-Final configs.

### Related Issues

https://github.com/CR6Community/Marlin/issues/302

### CODE REVIEW

**Comment by Sebazzz** [comment]
Same remark as in #304, use bed size divided by half. 🙃

**Comment by Thinkersbluff** [comment]
Here, I did not know how to submit two changes that are totally independent of each other, modify the same line of code, but may not both be approved.

If the actual change is ok to commit as is, we could update the #301 implementation to start from that new baseline, to achieve the same result.  Would that be ok?

**Comment by Thinkersbluff** [comment]
As I review the changes, though, I don't see the edit to line 80 that I made in the request I thought I submitted. 😳

Still learning how this GitHub works and my O'Reilly guidebook is way out of date...

I have updated the file in the pull request branch, to fix that.

**Comment by Sebazzz** [comment]
Is this PR still relevant now #304 got merged?

**Comment by Thinkersbluff** [comment]
> Is this PR still relevant now #304 got merged?

Yes please.  This one asks for a longer prime before the pattern starts.  I think it actually proposes to revert a change you made earlier, so you may have a reason to challenge this one.  I have depth perception issues up close to the nozzle and am not quick enough to snag that drool before the printer drags it into the pattern, with a priming of only 2mm…. If I forget or fail anyway at 15mm, it gives me a bigger blob to grab for, as it makes the tour of the bed. 🤪

**Comment by Sebazzz** [comment]
Apologies, I only focused on the duplicate BED_SIZE in the gcode that causes a conflict.

**Comment by Thinkersbluff** [comment]
Have I done the PR incorrectly?  You did ask me to change this PR to use BED_SIZE / 2, but I did that before the other PR was merged into extui.  I don’t see a conflict now, but if GitHub is seeing a conflict, what is it that Ihaveto change, to resolve that?

**Pull request closed without merging**
