### PR TITLE
reconfigured for 6 max

### PR DESCRIPTION
**Pull request by dabbodev**
### Requirements

* Filling out this template is required. Pull Requests without a clear description may be closed at the maintainers' discretion.

### Description

Reconfigured bed and boundary sizes for max as well as the grid size for abl.

### Benefits

MAX support

### CODE REVIEW

**Comment by Sebazzz** [comment]
Could you test one thing: If you ABL from the touch screen, do you see anything weird except for the fact that up to 16 points of leveling is shown?

**Comment by dabbodev** [comment]
Actually on the stock MAX firmware it was a 49 point grid as well. Here's a
photo of the screen:
https://drive.google.com/file/d/1LehyQLRUopP5cv27xvH4GqBfSA5JPeTe/view?usp=drivesdk

**Comment by dabbodev** [comment]
For me if I make it not a 49 point grid it gets weird on the screen

**Comment by dabbodev** [comment]
I also still only have the stock screen firmware installed. I never had to
reflash it.

**Comment by Sebazzz** [comment]
> I also still only have the stock screen firmware installed. I never had to reflash it.

In that case I assume you only print from a host like Octoprint? Otherwise you wouldn't be able to select files from the SD card and run into other weird issues.

**Comment by dabbodev** [comment]
Yeah just from hosts/octoprint so yeah i haven't tried printing local from
sd

**Comment by Sebazzz** [comment]
Thanks got it. If you have the time, I'd appreciate it if you could flash the CF4 screen firmware and try that.

**Comment by dabbodev** [comment]
So yep, it only shows 16 squares on the screen in the CFW but that
shouldn't be a hard fix to fork and change. I can probably do it pretty
quick just gotta whip up 49 icons ([hank hill] do I look like I know what a
jpeg is?) And update the icl for the firmware

**Comment by Sebazzz** [comment]
Forking the touch screen permanently is a pain, but adding 50 icons is fine and then we just use an offset if compiling for the Max.

Met vriendelijke groet,
Sebastiaan Dammann
________________________________
Van: David Giles <notifications@github.com>
Verzonden: Friday, December 25, 2020 1:57:24 AM
Aan: CR6Community/Marlin <Marlin@noreply.github.com>
CC: Sebastiaan Dammann <sebastiaandammann@outlook.com>; State change <state_change@noreply.github.com>
Onderwerp: Re: [CR6Community/Marlin] reconfigured for 6 max (#81)


So yep, it only shows 16 squares on the screen in the CFW but that
shouldn't be a hard fix to fork and change. I can probably do it pretty
quick just gotta whip up 49 icons ([hank hill] do I look like I know what a
jpeg is?) And update the icl for the firmware

**Pull request merged**
